const questions = [
  {
    id: 1,
    question: 'What does CPU stand for?',
    options: ['Central Processing Unit', 'Computer Power Unit', 'Central Print Unit', 'Control Panel Unit'],
    answer: 0,
  },
  {
    id: 2,
    question: 'What is the full form of RAM?',
    options: ['Read Access Memory', 'Random Access Memory', 'Run All Memory', 'Random Allocate Memory'],
    answer: 1,
  },
  {
    id: 3,
    question: 'What does HTML stand for?',
    options: ['HyperText Machine Language', 'HyperText Markup Language', 'HighText Markup Language', 'None of these'],
    answer: 1,
  },
  {
    id: 4,
    question: 'What does CSS stand for?',
    options: ['Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style Sheets', 'Colorful Style Sheets'],
    answer: 0,
  },
  {
    id: 5,
    question: 'What does HTTP stand for?',
    options: ['HyperText Transfer Protocol', 'HighText Transfer Protocol', 'Hyper Transfer Text Protocol', 'None'],
    answer: 0,
  },
  {
    id: 6,
    question: 'Which language runs in a web browser?',
    options: ['Java', 'C', 'Python', 'JavaScript'],
    answer: 3,
  },
  {
    id: 7,
    question: 'What does SQL stand for?',
    options: ['Structured Query Language', 'Stylish Question Language', 'Statement Question Language', 'Stylesheet Query Language'],
    answer: 0,
  },
  {
    id: 8,
    question: 'Which is a JavaScript framework?',
    options: ['Laravel', 'Django', 'React', 'Flask'],
    answer: 2,
  },
  {
    id: 9,
    question: 'What year was JavaScript launched?',
    options: ['1996', '1995', '1994', 'None of the above'],
    answer: 1,
  },
  {
    id: 10,
    question: 'What does API stand for?',
    options: ['Application Programming Interface', 'Application Process Interface', 'Application Programming Internet', 'None'],
    answer: 0,
  },
  {
    id: 11,
    question: 'Which one is not a programming language?',
    options: ['Python', 'HTML', 'Java', 'C++'],
    answer: 1,
  },
  {
    id: 12,
    question: 'What is the brain of the computer?',
    options: ['RAM', 'Hard Drive', 'Motherboard', 'CPU'],
    answer: 3,
  },
  {
    id: 13,
    question: 'Which company developed Windows OS?',
    options: ['Apple', 'Microsoft', 'IBM', 'Google'],
    answer: 1,
  },
  {
    id: 14,
    question: 'Which device is used to input data into a computer?',
    options: ['Monitor', 'Printer', 'Mouse', 'Speaker'],
    answer: 2,
  },
  {
    id: 15,
    question: 'Which protocol is used to send emails?',
    options: ['SMTP', 'FTP', 'HTTP', 'SSH'],
    answer: 0,
  },
  {
    id: 16,
    question: 'Which tag is used to insert an image in HTML?',
    options: ['<img>', '<image>', '<pic>', '<src>'],
    answer: 0,
  },
  {
    id: 17,
    question: 'What is the full form of USB?',
    options: ['Universal Serial Bus', 'Unique System Bus', 'Universal System Base', 'None'],
    answer: 0,
  },
  {
    id: 18,
    question: 'Which of these is not an operating system?',
    options: ['Windows', 'Linux', 'Oracle', 'macOS'],
    answer: 2,
  },
  {
    id: 19,
    question: 'What is the default port of HTTP?',
    options: ['21', '80', '443', '8080'],
    answer: 1,
  },
  {
    id: 20,
    question: 'Which company owns the Android OS?',
    options: ['Apple', 'Google', 'Microsoft', 'Samsung'],
    answer: 1,
  },
  {
    id: 21,
    question: 'What does DNS stand for?',
    options: ['Domain Name System', 'Digital Network System', 'Distributed Name Service', 'Domain Network Service'],
    answer: 0,
  },
  {
    id: 22,
    question: 'Which language is used for styling web pages?',
    options: ['HTML', 'JQuery', 'CSS', 'XML'],
    answer: 2,
  },
  {
    id: 23,
    question: 'How many bits are there in a byte?',
    options: ['4', '8', '16', '32'],
    answer: 1,
  },
  {
    id: 24,
    question: 'Which is the most secure password?',
    options: ['12345678', 'qwerty', 'P@ssw0rd!', 'password'],
    answer: 2,
  },
  {
    id: 25,
    question: 'What does LAN stand for?',
    options: ['Large Area Network', 'Local Area Network', 'Light Access Network', 'None'],
    answer: 1,
  },
  {
    id: 26,
    question: 'Which tag is used to create a hyperlink in HTML?',
    options: ['<link>', '<a>', '<href>', '<url>'],
    answer: 1,
  },
  {
    id: 27,
    question: 'What does OS stand for?',
    options: ['Operating System', 'Open Software', 'Output System', 'Optical Storage'],
    answer: 0,
  },
  {
    id: 28,
    question: 'Which programming language is used for iOS app development?',
    options: ['Java', 'Swift', 'Kotlin', 'Python'],
    answer: 1,
  },
  {
    id: 29,
    question: 'Which HTML attribute is used to define inline styles?',
    options: ['style', 'class', 'font', 'styles'],
    answer: 0,
  },
  {
    id: 30,
    question: 'Which of the following is a NoSQL database?',
    options: ['MySQL', 'MongoDB', 'PostgreSQL', 'Oracle'],
    answer: 1,
  },
];

export default questions;
